name: Build Application Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install libraries
        run: pip install -r requirements.txt -t .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install test dependencies
        run: pip install -r test-requirements.txt -t .
      - name: Run tests
        run: pytest

